### ISSUE TITLE
Downloads: setState Memory Leak when using Timer

### ISSUE THREAD

**Issue by Y0ngg4n** [jmshrv/finamp#329]
Download a playlist and check the log.

```
E/flutter (27375): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (27375): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1078:9)
E/flutter (27375): #1      State.setState (package:flutter/src/widgets/framework.dart:1113:6)
E/flutter (27375): #2      _DownloadedIndicatorState.initState.<anonymous closure> (package:finamp/components/AlbumScreen/downloaded_indicator.dart:45:9)
E/flutter (27375): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (27375): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (27375): #5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (27375): #6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (27375): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (27375): #8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (27375): #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (27375): 
I/flutter (27375): [DownloadsHelper/INFO] 2022-09-21 21:39:38.231149: Downloading image for Life Is A Highway (023f60ea2b42ac0cc940cd7b2d84001b) as it has its own image
E/flutter (27375): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: setState() called after dispose(): _DownloadedIndicatorState#04b18(lifecycle state: defunct, not mounted)
E/flutter (27375): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (27375): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
```

**Comment by jmshrv** [comment]
This should be fixed with 71075fc
