### ISSUE TITLE
Issue when conecting to my jellyfin server

### ISSUE THREAD

**Issue by meritarition** [jmshrv/finamp#812]
Hi, I used finamp previously for quite some time but stop because I wanted to have an android auto music player. Now that android auto is supported, I wanted to use finamp again but when I select my server I get this error. ![IMG_20240716_134252.jpg](https://github.com/user-attachments/assets/82a0ed0b-b71a-4395-b994-0c275295ddd2)

I'm not shure where is the problem. Is it an issue with my jellyfin installation ? I'm connecting to jelllyfin with a caddy reverse proxy maybe the problem is comming from there ?

Thanks in advance.

**Comment by jmshrv** [comment]
Error code 500 means that something is going wrong on the server. Are there any errors showing in your Jellyfin logs?

**Comment by meritarition** [comment]
In fact there is one. It is talking about NULL, not sure why.

`2024-07-17T15:13:46.510728514Z [15:13:46] [ERR] Error processing request. URL GET /Users/89173d5636a347e9803d587577ee22ca/Items.
2024-07-17T15:13:46.510782833Z System.InvalidOperationException: The data is NULL at ordinal 1. This method can't be called on NULL values. Check using IsDBNull before calling.
2024-07-17T15:13:46.510791386Z    at Microsoft.Data.Sqlite.SqliteDataRecord.GetNull[T](Int32 ordinal)
2024-07-17T15:13:46.510798890Z    at Microsoft.Data.Sqlite.SqliteValueReader.GetBlob(Int32 ordinal)
2024-07-17T15:13:46.510806033Z    at Microsoft.Data.Sqlite.SqliteDataRecord.GetCachedBlob(Int32 ordinal)
2024-07-17T15:13:46.510813094Z    at Microsoft.Data.Sqlite.SqliteDataRecord.GetStream(Int32 ordinal)
2024-07-17T15:13:46.510820273Z    at Emby.Server.Implementations.Data.SqliteItemRepository.GetItem(SqliteDataReader reader, InternalItemsQuery query, Boolean enableProgramAttributes, Boolean hasEpisodeAttributes, Boolean hasServiceName, Boolean queryHasStartDate, Boolean hasTrailerTypes, Boolean hasArtistFields, Boolean hasSeriesFields, Boolean skipDeserialization)
2024-07-17T15:13:46.510841795Z    at Emby.Server.Implementations.Data.SqliteItemRepository.GetItemList(InternalItemsQuery query)
2024-07-17T15:13:46.510849548Z    at MediaBrowser.Controller.Entities.Folder.AddChildrenToList(Dictionary`2 result, Boolean includeLinkedChildren, Boolean recursive, Func`2 filter)
2024-07-17T15:13:46.510856986Z    at MediaBrowser.Controller.Entities.Folder.GetRecursiveChildren(Func`2 filter)
2024-07-17T15:13:46.510864092Z    at MediaBrowser.Controller.Entities.Audio.MusicAlbum.get_Tracks()
2024-07-17T15:13:46.510871025Z    at MediaBrowser.Controller.Entities.Audio.MusicAlbum.GetEligibleChildrenForRecursiveChildren(User user)
2024-07-17T15:13:46.510878183Z    at MediaBrowser.Controller.Entities.Folder.GetChildren(User user, Boolean includeLinkedChildren, InternalItemsQuery query)
2024-07-17T15:13:46.510917846Z    at MediaBrowser.Controller.Entities.Folder.GetItemsInternal(InternalItemsQuery query)
2024-07-17T15:13:46.510925337Z    at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)
2024-07-17T15:13:46.510932399Z    at MediaBrowser.Controller.Entities.Folder.GetChildCount(User user)
2024-07-17T15:13:46.510939671Z    at Emby.Server.Implementations.Dto.DtoService.AttachUserSpecificInfo(BaseItemDto dto, BaseItem item, User user, DtoOptions options)
2024-07-17T15:13:46.510947033Z    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
2024-07-17T15:13:46.510955821Z    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtos(IReadOnlyList`1 items, DtoOptions options, User user, BaseItem owner)
2024-07-17T15:13:46.510965304Z    at Jellyfin.Api.Controllers.ItemsController.GetItems(Nullable`1 userId, String maxOfficialRating, Nullable`1 hasThemeSong, Nullable`1 hasThemeVideo, Nullable`1 hasSubtitles, Nullable`1 hasSpecialFeature, Nullable`1 hasTrailer, Nullable`1 adjacentTo, Nullable`1 parentIndexNumber, Nullable`1 hasParentalRating, Nullable`1 isHd, Nullable`1 is4K, LocationType[] locationTypes, LocationType[] excludeLocationTypes, Nullable`1 isMissing, Nullable`1 isUnaired, Nullable`1 minCommunityRating, Nullable`1 minCriticRating, Nullable`1 minPremiereDate, Nullable`1 minDateLastSaved, Nullable`1 minDateLastSavedForUser, Nullable`1 maxPremiereDate, Nullable`1 hasOverview, Nullable`1 hasImdbId, Nullable`1 hasTmdbId, Nullable`1 hasTvdbId, Nullable`1 isMovie, Nullable`1 isSeries, Nullable`1 isNews, Nullable`1 isKids, Nullable`1 isSports, Guid[] excludeItemIds, Nullable`1 startIndex, Nullable`1 limit, Nullable`1 recursive, String searchTerm, SortOrder[] sortOrder, Nullable`1 parentId, ItemFields[] fields, BaseItemKind[] excludeItemTypes, BaseItemKind[] includeItemTypes, ItemFilter[] filters, Nullable`1 isFavorite, MediaType[] mediaTypes, ImageType[] imageTypes, ItemSortBy[] sortBy, Nullable`1 isPlayed, String[] genres, String[] officialRatings, String[] tags, Int32[] years, Nullable`1 enableUserData, Nullable`1 imageTypeLimit, ImageType[] enableImageTypes, String person, Guid[] personIds, String[] personTypes, String[] studios, String[] artists, Guid[] excludeArtistIds, Guid[] artistIds, Guid[] albumArtistIds, Guid[] contributingArtistIds, String[] albums, Guid[] albumIds, Guid[] ids, VideoType[] videoTypes, String minOfficialRating, Nullable`1 isLocked, Nullable`1 isPlaceHolder, Nullable`1 hasOfficialRating, Nullable`1 collapseBoxSetItems, Nullable`1 minWidth, Nullable`1 minHeight, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 is3D, SeriesStatus[] seriesStatus, String nameStartsWithOrGreater, String nameStartsWith, String nameLessThan, Guid[] studioIds, Guid[] genreIds, Boolean enableTotalRecordCount, Nullable`1 enableImages)
2024-07-17T15:13:46.510992179Z    at Jellyfin.Api.Controllers.ItemsController.GetItemsByUserIdLegacy(Guid userId, String maxOfficialRating, Nullable`1 hasThemeSong, Nullable`1 hasThemeVideo, Nullable`1 hasSubtitles, Nullable`1 hasSpecialFeature, Nullable`1 hasTrailer, Nullable`1 adjacentTo, Nullable`1 parentIndexNumber, Nullable`1 hasParentalRating, Nullable`1 isHd, Nullable`1 is4K, LocationType[] locationTypes, LocationType[] excludeLocationTypes, Nullable`1 isMissing, Nullable`1 isUnaired, Nullable`1 minCommunityRating, Nullable`1 minCriticRating, Nullable`1 minPremiereDate, Nullable`1 minDateLastSaved, Nullable`1 minDateLastSavedForUser, Nullable`1 maxPremiereDate, Nullable`1 hasOverview, Nullable`1 hasImdbId, Nullable`1 hasTmdbId, Nullable`1 hasTvdbId, Nullable`1 isMovie, Nullable`1 isSeries, Nullable`1 isNews, Nullable`1 isKids, Nullable`1 isSports, Guid[] excludeItemIds, Nullable`1 startIndex, Nullable`1 limit, Nullable`1 recursive, String searchTerm, SortOrder[] sortOrder, Nullable`1 parentId, ItemFields[] fields, BaseItemKind[] excludeItemTypes, BaseItemKind[] includeItemTypes, ItemFilter[] filters, Nullable`1 isFavorite, MediaType[] mediaTypes, ImageType[] imageTypes, ItemSortBy[] sortBy, Nullable`1 isPlayed, String[] genres, String[] officialRatings, String[] tags, Int32[] years, Nullable`1 enableUserData, Nullable`1 imageTypeLimit, ImageType[] enableImageTypes, String person, Guid[] personIds, String[] personTypes, String[] studios, String[] artists, Guid[] excludeArtistIds, Guid[] artistIds, Guid[] albumArtistIds, Guid[] contributingArtistIds, String[] albums, Guid[] albumIds, Guid[] ids, VideoType[] videoTypes, String minOfficialRating, Nullable`1 isLocked, Nullable`1 isPlaceHolder, Nullable`1 hasOfficialRating, Nullable`1 collapseBoxSetItems, Nullable`1 minWidth, Nullable`1 minHeight, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 is3D, SeriesStatus[] seriesStatus, String nameStartsWithOrGreater, String nameStartsWith, String nameLessThan, Guid[] studioIds, Guid[] genreIds, Boolean enableTotalRecordCount, Nullable`1 enableImages)
2024-07-17T15:13:46.511007172Z    at lambda_method1131(Closure, Object, Object[])
2024-07-17T15:13:46.511014218Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
2024-07-17T15:13:46.511021421Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-07-17T15:13:46.511029208Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
2024-07-17T15:13:46.512016458Z --- End of stack trace from previous location ---
2024-07-17T15:13:46.512032383Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2024-07-17T15:13:46.512040545Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-07-17T15:13:46.512048371Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2024-07-17T15:13:46.512055565Z --- End of stack trace from previous location ---
2024-07-17T15:13:46.512071312Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-07-17T15:13:46.512079652Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-07-17T15:13:46.512086885Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-07-17T15:13:46.512094344Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2024-07-17T15:13:46.512101354Z --- End of stack trace from previous location ---
2024-07-17T15:13:46.512108241Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-07-17T15:13:46.512115700Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-07-17T15:13:46.512123210Z    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
2024-07-17T15:13:46.512181579Z    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
2024-07-17T15:13:46.512190665Z    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
2024-07-17T15:13:46.513068057Z    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
2024-07-17T15:13:46.513084307Z    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2024-07-17T15:13:46.513092193Z    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
2024-07-17T15:13:46.513099417Z    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
2024-07-17T15:13:46.513106406Z    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2024-07-17T15:13:46.513113399Z    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
2024-07-17T15:13:46.513120532Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2024-07-17T15:13:46.513127516Z    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
2024-07-17T15:13:46.513134529Z    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
2024-07-17T15:13:46.513144523Z    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
2024-07-17T15:13:46.513151705Z    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
2024-07-17T15:13:46.513159080Z    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)


`

**Comment by TheParaTiger** [comment]
It looks like your Jellyfin Server doesn't find the necessary files in your server's library (the files that point to the location of your existing music files)

Could also be a corrupted library.db file

**Comment by Chaphasilor** [comment]
@meritarition is everything working without errors in the Jellyfin web client?

**Comment by meritarition** [comment]
Thanks, I didn't thought of checking other client but neither the jellyfin android app nor the web client find my songs, I don't know why. I'm closing the issue and I'm gonna look for help with the jellyfin people. Thanks again!

**Comment by Chaphasilor** [comment]
Okay, best of luck then!
